export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_DELETE = 'ERROR_DELETE';
export const ERROR_FETCH = 'ERROR_FETCH';
export const REGISTER = 'REGISTER';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PROGRESS = 'GET_PROGRESS';

export const GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN';
export const GOOGLE_SIGN_OUT = 'GOOGLE_SIGN_OUT';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';

export const DETAIL_UPDATING_SUCCESS = 'DETAIL_UPDATING_SUCCESS';
export const DETAIL_UPDATING_FAIL = 'DETAIL_UPDATING_FAIL';

export const USERS_LOADING_SUCCESS = 'USERS_LOADING_SUCCESS';
export const USERS_LOADING_FAIL = 'USERS_LOADING_FAIL';
export const USER_ACTIVATE_SUCCESS = 'USER_ACTIVATE_SUCCESS';
export const USER_ACTIVATE_FAIL = 'USER_ACTIVATE_FAIL';

export const ATTENDANCE_UPDATE_SUCCESS = 'ATTENDANCE_UPDATE_SUCCESS';
export const ATTENDANCE_UPDATE_FAIL = 'ATTENDANCE_UPDATE_FAIL';
